# Generated by Django 2.1.7 on 2019-05-10 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_auto_20190510_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 9, 16, 44, 139806, tzinfo=utc)),
        ),
    ]
