# Generated by Django 2.1.7 on 2019-05-10 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0003_auto_20190510_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 19, 2, 50, 319931)),
        ),
    ]
